### ISSUE TITLE
Support for persisted queries

### ISSUE THREAD

**Issue by brezinajn** [apollographql/apollo-kotlin-execution#16]
Currently there is no way to hook in an adapter to handle persisted queries. If this issue is out of scope of intended features, please feel free to close it.

**Comment by martinbonnin** [comment]
I just transferred the issue to https://github.com/apollographql/apollo-kotlin-execution/ but I'm actually not sure if this is the good place. Are you building a client or a server?

**Comment by brezinajn** [comment]
A server. Since `Application::apolloModule` lives in `com.apollographql.execution.ktor` this looks like it might be the right place. Thank you

**Comment by martinbonnin** [comment]
Nice! We're in the right spot 👍 

I think you should be able to add persisted queries using `ExecutableSchema.Builder.persistedDocumentCache()`:


```
    val executableSchema = MyExecutableSchemaBuilder()
        .persistedDocumentCache(InMemoryPersistedDocumentCache())
        .build()

    embeddedServer(Netty, port = 8080, host = "0.0.0.0") {
      install(CORS) {
        anyHost()
        allowHeaders {
          true
        }
        allowNonSimpleContentTypes = true
      }
      apolloModule(executableSchema)
    }.start(wait = true)
```

Heads up that this whole repo is in its very early days so use at your own risks

**Comment by martinbonnin** [comment]
> Not having access to ApplicationCall (ktor specific) makes authentication not really viable.

I think you can have global authentication but maybe not per-endpoint? (https://ktor.io/docs/server-auth.html#configure)

Do not hesitate to share the API of what you'd like to see, or even a pull request.

**Comment by brezinajn** [comment]
That's not the issue. The issue is not having a call context in the resolver. Let's say I want to enable user to edit his own username (and of course not username of anyone else)

Quick, single file demonstration
``` Kotlin
package com.example

import com.apollographql.execution.annotation.GraphQLQueryRoot
import com.apollographql.execution.ktor.respondGraphQL
import io.ktor.server.application.*
import io.ktor.server.auth.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.routing.*

fun main() {
    embeddedServer(Netty, port = 8080, host = "0.0.0.0", module = Application::module)
        .start(wait = true)
}

fun Application.module() {
    val executableSchema = ServiceExecutableSchemaBuilder().build()

    authentication {
        basic(name = "myauth") {
            validate { credentials ->
                getUserByCredentials(credentials)?.let { UserIdPrincipal(it.id) }
            }
        }
    }

    routing {
        authenticate("myauth") {
            post("graphql") {
                call.respondGraphQL(executableSchema)
            }
        }
    }
}

@GraphQLQueryRoot
class Query {
    /**
     * Updates own username
     */
    fun ApplicationCall.updateOwnUsername(name: String) {
        val userId = principal<UserIdPrincipal>()!!.id

        updateUsernameById(userId, name)
    }
}

data class UserIdPrincipal(val id: Int) : Principal

data class User(val id: Int, val name: String)

fun getUserByCredentials(credentials: UserPasswordCredential): User? {
    TODO()
}

fun updateUsernameById(id: Int, name: String) {
    TODO()
}
```

The thing is, without `updateOwnUsername` having an access to the context of the call, I'm unable to access the principal, so I can't get info on who's making the request.

If we agree on a way to proceed, I can cook up a PR.

I think the main question is, how to approach the problem of providing context in a server agnostic way, to support both http4k and Ktor.

**Comment by brezinajn** [comment]
Works like a charm. You're probably right. It might be better to let users choose level of abstraction that fits their needs..
