### ISSUE TITLE
Support for suspending resolvers

### ISSUE THREAD

**Issue by brezinajn** [apollographql/apollo-kotlin-execution#18]
It would be handy to have a first party support for suspending functions

``` Kotlin
@GraphQLQueryRoot
class Query{
    suspend fun foo(): Int {
        ...
    }
} {
```

There are some alternatives but are very non-idiomatic and/or have performance implications (blocking).

**Comment by martinbonnin** [comment]
+1. Coroutine support + parallel execution is one of the big things to be worked on.

**Comment by martinbonnin** [comment]
Fixed with https://github.com/apollographql/apollo-kotlin-execution/commit/45de34420a633a22a3153a3c189f772f508ea000
